server:
  port: 8080
spring.devtools.remote.secret: mysecret
spring.thymeleaf.templateResolverOrder: 1
spring.thymeleaf.cache: false
parameters:
  intKeys:
  - flatRooms
  doubleKeys:
  - price
  - flatArea
  stringKeys:
  - regionName
  boolKeys:
  - haveBalcony
